# Generated by Django 4.1.7 on 2023-03-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='child',
            new_name='childs',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='choice_text',
            new_name='parents',
        ),
        migrations.RemoveField(
            model_name='family',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='family',
            name='votes',
        ),
        migrations.AddField(
            model_name='family',
            name='informations',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.DateTimeField(verbose_name='year first_seen'),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
