# Generated by Django 4.1.7 on 2023-03-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_child_family_childs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childs',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.DateTimeField(null=True, verbose_name='year last_seen'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
