# Generated by Django 4.1.7 on 2023-03-04 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_family_childs_alter_family_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='childs',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.DateField(validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter a valid year.')], verbose_name='year first seen'),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Enter a valid year.')], verbose_name='year last_seen'),
        ),
        migrations.AlterField(
            model_name='family',
            name='parents',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
