# Generated by Django 4.1.7 on 2023-03-04 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_family_childs_alter_family_first_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='informations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
