# Generated by Django 4.1.7 on 2023-03-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_family_informations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.DateField(verbose_name='year first seen'),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.DateField(blank=True, null=True, verbose_name='year last_seen'),
        ),
    ]
