# Generated by Django 4.1.7 on 2023-03-04 21:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_family_first_seen_alter_family_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)]),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(200), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
