# Generated by Django 4.1.7 on 2023-03-05 11:05

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='informations',
            field=models.TextField(blank=True, default=polls.models.Family.default_json, null=True),
        ),
    ]
