# Generated by Django 4.1.7 on 2023-03-05 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_family_informations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='childs',
        ),
        migrations.AddField(
            model_name='family',
            name='alias',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='family',
            name='bot_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='family',
            name='open_source',
            field=models.BooleanField(default=False),
        ),
    ]
