# Generated by Django 4.1.7 on 2023-03-05 13:52

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_family_childs_family_alias_family_bot_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='informations',
            field=models.JSONField(blank=True, default=dict, help_text=polls.models.Family.default_json, null=True),
        ),
    ]
