# Generated by Django 4.1.7 on 2023-03-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_family_white_malware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
