# Generated by Django 4.1.7 on 2023-03-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_family_first_seen_alter_family_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
