# Generated by Django 4.1.7 on 2023-03-17 17:38

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_alter_family_first_seen_alter_family_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.TextField(max_length=7, validators=[polls.models.validate_year_month]),
        ),
        migrations.AlterField(
            model_name='family',
            name='last_seen',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[polls.models.validate_year_month]),
        ),
    ]
