# Generated by Django 4.1.7 on 2023-03-17 17:39

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_alter_family_first_seen_alter_family_last_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='first_seen',
            field=models.CharField(max_length=7, validators=[polls.models.validate_year_month]),
        ),
    ]
