# Generated by Django 4.1.7 on 2023-05-07 16:53

from django.db import migrations, models
import polls.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_alter_family_first_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='informations',
            field=models.JSONField(blank=True, default=polls.models.Family.default_json, null=True),
        ),
    ]
