# Generated by Django 5.0.4 on 2026-02-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_family_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='parent_families',
            field=models.ManyToManyField(blank=True, related_name='children', to='polls.family'),
        ),
    ]
