# Generated by Django 5.0.4 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0025_remove_old_parents_rename_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='events',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
